### ISSUE TITLE
switching to OO

### ISSUE THREAD

**Issue by wolberd** [People-Museum-Project/PeopleCode-OpenAI-Library#3]
Let's switch to an OO version as the main lib. With functional, we need either globals or lots of params, and the OO can still be simple enough for novice Pythoners (our target)

OO version: need the following tweaks, then modify all samples to use this lib.

	rename lib file “PeopleCodeOpenAI.py”

        lets call it class OpenAI_Conversation, not Assistant, to avoid that term “Assistant” since we are using assistant API for RAG

	data members: client, model, api_key, assistant, prevConversation
		by default model=”gpt-4’ assistant is None, prevConversation is []
		constructor takes key and optional model, assistant

	simpler ask_question:

	ask_question(instructions, question, includePrevConvo=True)

		note reorder of params

                don’t need client, model, assistant, prevConversation as params since they are data members

	        return value is just a string (since prevConversation is data member)

	provide setModel, setAssistant, getConversation methods

don’t need personid...dont integrate this lib directly with person db, instead we’ll send in person name and description in “instructions” param of questions

need to tweak all samples and test them

************* 
I don’t think we should keep functional version, maybe mark it as v 0.9, it has globals and oo version only requires complication of object creation and oo call syntax for beginning coders, so it can work

If we do keep
rename lib file “PeopleCodeOpenAI.py”, will need to modify all samples

settings is a global set, we can remove
	just have model and temperature params with default values

client and api_key are also globals in the library. We do want a client that persists across calls. This is where OO comes in

generateSamplePrompts is currently used for followups as well, with a boolean param followups...lets discuss, maybe separate functions

conversation is currently a param sent in. give it a default param value of []. I don’t think we need to return it, if client sends one in, any additions to it will be manifest in list argument sent in. This will allow return value of ask_question to be a simple String (the response only) instead of a dictionary.

reorder params of ask_question and ask_assistant_question:

e.g., ask_question(conversation, question, instructions, assistant_id=None):

will instead be ask_question(instructions, question, conversation=[], assistant_id=None, model=’gpt-4’)

	maybe add temperature?

**Comment by kzahiri1** [comment]
Made changes. The new OO version is PeopleCodeOpenAI.py. All samples now utilize this.

**Comment by kzahiri1** [comment]
Made changes. The new OO version is PeopleCodeOpenAI.py. All samples now utilize this.
