### ISSUE TITLE
comments on oo version 1

### ISSUE THREAD

**Issue by wolberd** [People-Museum-Project/PeopleCode-OpenAI-Library#4]
Great work on this.

What is "set_context" and it has "pass" in it? Eliminate?

Lets talk about  "followups" param in "generate_sample_prompts? It is used in the instructions but I don't understand why/how.
Maybe just have separate functions, one is generate_sample_questions and one is generate_followups...for the latter, can use prevConvo to send last Q/A as the context

One new function would be "generateList(list_description, numItems, maxWordsPerItem)" which returns a list of text.

**Comment by kzahiri1** [comment]
set_context is just a temporary function in case there's a need, which isn't being used right now. I also think it's best to eliminate it, which I'll do. 
Followups are just used in generate_sample_prompts and in the instructions to dictate whether or not to generate follow-up questions. If not, then sample prompts will be generated. I agree that it would be best to have two separate functions for this. I can do that. Please let me know.
I have some questions about generateList. What is this and what would it be used for? What is in the list of text?

**Comment by wolberd** [comment]
Hi Kayvan. Good on first two items.

On generateList, say you want a list of the top SF giants outfielders. You
send list description, and function returns a list. Probably best way to
implement is by asking OpenAI to create a list with delimiters in between
each item, e.g., '%%' and instructing it not to add anything else. Then you
can split the result in your function to create the list. I think we do
something similar with the generate_sample_prompts, this function would be
used to get a list of something in general

On Wed, Aug 7, 2024 at 3:26 PM Kayvan Zahiri ***@***.***>
wrote:

> set_context is just a temporary function in case there's a need, which
> isn't being used right now. I also think it's best to eliminate it, which
> I'll do.
> Followups are just used in generate_sample_prompts and in the instructions
> to dictate whether or not to generate follow-up questions. If not, then
> sample prompts will be generated. I agree that it would be best to have two
> separate functions for this. I can do that. Please let me know.
> I have some questions about generateList. What is this and what would it
> be used for? What is in the list of text?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_People-2DMuseum-2DProject_PeopleCode-2DOpenAI-2DLibrary_issues_4-23issuecomment-2D2274453480&d=DwMFaQ&c=qgVugHHq3rzouXkEXdxBNQ&r=FEMIjhnbuZeFlLHoxSCKdfNQV8MJpYa6-Woegm-5hjI&m=KPjxPvgIBDFMtZClDxz-G6BZyS2m0t17NpPc_I_gFtQMNRLwOhK2_UdP7a-Bw1ow&s=-dkDfllHEjC8mFMHldKDJR06LFnLTVNQBy1R9gjWY8o&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAHZ766LAJS64XHGHPYRMN3ZQKNJTAVCNFSM6AAAAABMFGMIOOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENZUGQ2TGNBYGA&d=DwMFaQ&c=qgVugHHq3rzouXkEXdxBNQ&r=FEMIjhnbuZeFlLHoxSCKdfNQV8MJpYa6-Woegm-5hjI&m=KPjxPvgIBDFMtZClDxz-G6BZyS2m0t17NpPc_I_gFtQMNRLwOhK2_UdP7a-Bw1ow&s=vocusWO9jBtjQK_zvw8xWrtcUsWQuS5XhitnkVe_oNQ&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> <People-Museum-Project/PeopleCode-OpenAI-Library/issues/4/2274453480@
> github.com>
>


-- 
David Wolber
Professor, University of San Francisco
DragAndDropCode.com, AppInventor.org

**Comment by kzahiri1** [comment]
I made all the changes. I also added a command line and streamlit sample where the new generate_list is/can be used.

**Comment by wolberd** [comment]
awesome, good work!

On Fri, Aug 9, 2024 at 2:59 PM Kayvan Zahiri ***@***.***>
wrote:

> I made all the changes. I also added a command line and streamlit sample
> where the new generate_list is/can be used.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_People-2DMuseum-2DProject_PeopleCode-2DOpenAI-2DLibrary_issues_4-23issuecomment-2D2278805946&d=DwMFaQ&c=qgVugHHq3rzouXkEXdxBNQ&r=FEMIjhnbuZeFlLHoxSCKdfNQV8MJpYa6-Woegm-5hjI&m=x4vb1e9-T6OWAV6U9CWt6O1i_cEMXocKeTrGd6RCBzqpY6jN2njMpbiDxhhfYcbI&s=-_IIjvmB4KLJOAq_nTooLQWkHkTvqYvCRTzqX2YwqWg&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAHZ76ZY2TIW2SPKFVNSB3LZQU3VBAVCNFSM6AAAAABMFGMIOOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENZYHAYDKOJUGY&d=DwMFaQ&c=qgVugHHq3rzouXkEXdxBNQ&r=FEMIjhnbuZeFlLHoxSCKdfNQV8MJpYa6-Woegm-5hjI&m=x4vb1e9-T6OWAV6U9CWt6O1i_cEMXocKeTrGd6RCBzqpY6jN2njMpbiDxhhfYcbI&s=RrBs4Mx8iD0uVBfJei7B_D3bf7bH3vIhKNgCMEGbTz0&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> <People-Museum-Project/PeopleCode-OpenAI-Library/issues/4/2278805946@
> github.com>
>


-- 
David Wolber
Professor, University of San Francisco
DragAndDropCode.com, AppInventor.org
