### ISSUE TITLE
tweeks for library and samples

### ISSUE THREAD

**Issue by wolberd** [People-Museum-Project/PeopleCode-OpenAI-Library#5]
Hi Kayvan, good job on the new version of the library. I have some thoughts. Read these, then let's discuss and go over

library-- can we just send back a string with the reply from "ask_question" (and similar functions)? We have a data member with the conversation, so we don't need to send it back and the client can always get it. This would simplify things so client need not understand dictionaries in order to do simple ask question.

simplestChatApp sample -- I want this to have the simplest python possible. I think we can modify the library and the sample to do this. name the variable api_key a different name so it isn't named same as parameter to constructor. Eliminate "conversation" variable

simpleChatAppStreamlit -- this line: " openai_conversation._OpenAI_Conversation__prevConversation = st.session_state.conversation" seems like we can eliminate. Can we store the entire openai_conversation object in the state, and it keeps track of the prevConversation, so we don't have to do what you're doing with that line??

I think there are probably similar changes that can be made in other samples. But just a few tweeks I think.

**Comment by kzahiri1** [comment]
The changes have been made. Strings are returned from the necessary functions. A PreviousVersion folder has been created for the old library file. The samples have also been adjusted.

**Comment by kzahiri1** [comment]
Cool to hear, thank you.
